# Making the prompt a single line instead of two
[line_break]
disable = true

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ](bold red) "
vicmd_symbol = "[â¯](bold green)"
# error_symbol = "[âœ–](bold red) "

# Shows memory usage
[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

# Shows time
[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = false
